language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "ImproperMelon"
  - git config user.email 2422048218@qq.com
  - git add .
  - git commit -m "Update"
  - git push --force --quiet "https://${ACCESS_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/ImproperMelon/ImproperMelon.github.io.git
