language: node_js
sudo: false
node_js:
- 8
branches:
  only:
  - master
before_install:
- git config --global user.name 'ImproperMelon'
- git config --global user.email 2422048218@qq.com
- sed -i'' "s~https://github.com/ImproperMelon/ImproperMelon.github.io.git~https://${Github-Access-Token}@github.com/ImproperMelon/ImproperMelon.github.io.git~" _config.yml
install:
- npm install hexo-cli -g
- npm install
script:
- npm run deploy
