language: node_js
sudo: false
node_js:
- 8
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_26395f532ba9_key -iv $encrypted_26395f532ba9_iv
  -in id_rsa.enc -out id_rsa -d
- cp  .travis/id_rsa ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'ImproperMelon'
- git config --global user.email 2422048218@qq.com
install:
- npm install hexo-cli -g
- npm install
script:
- npm run deploy
