language: node_js
sudo: false
node_js:
- 8
branches:
  only:
  - master
before_install:
- sed -i'' "s~git@github.com:~https://${ACCESS_TOKEN}@github.com/~" _config.yml
- git config --global user.name 'ImproperMelon'
- git config --global user.email 2422048218@qq.com
install:
- npm install hexo-cli -g
- npm install
script:
- npm run deploy
cache:
  directories:
    - node_modules